baseurl = "https://www.example.org/"
title = "Kevin's Blog"
copyright = "Copyright &copy; 2019 - Kevin"
canonifyurls = true
theme = "kiera"
themesDir = "themes"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Kevin Xiao"
    github = "yunpengxiao"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "A place for Kevin to share his life"
    customCSS = []  #Optional Customised CSS
